apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kdbluunfr-java-springboot
  janus-idp.io/tekton: kdbluunfr-java-springboot
  backstage.io/kubernetes-id: kdbluunfr-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kdbluunfr-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
